from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

from tests.conftest import REPO_ROOT

SKETCH = REPO_ROOT / "arduino/phyphox_ble_sense/phyphox_ble_sense.ino"
CONTRACT = REPO_ROOT / "protocol/contract.json"
PROPERTIES = {"notify": "BLENotify", "read": "BLERead", "write": "BLEWrite"}


def _cpp_properties(access: list[str]) -> str:
    return " | ".join(PROPERTIES[name] for name in access)


def _cpp_ints(values: list[int]) -> str:
    return "{" + ", ".join(str(value) for value in values) + "}"


def _expected_header() -> str:
    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    bluetooth = contract["bluetooth"]
    frame = contract["frame"]
    selection = frame["config"]["selection"]
    modes = contract["modes"]
    offsets = _cpp_ints([field["offset"] for field in frame["data"]["fields"]])
    return f"""#pragma once
// Generated by test_behavior.py from protocol/contract.json.
#include <ArduinoBLE.h>
#include <cstddef>

constexpr const char* expectedDeviceName = {json.dumps(contract["device"]["name"])};
constexpr const char* expectedServiceUuid = {json.dumps(bluetooth["service_uuid"])};
constexpr const char* expectedDataUuid = {json.dumps(bluetooth["data_char_uuid"])};
constexpr const char* expectedConfigUuid = {json.dumps(bluetooth["config_char_uuid"])};
constexpr int expectedDataSize = {frame["data"]["byte_length"]};
constexpr int expectedConfigSize = {frame["config"]["byte_length"]};
constexpr int expectedSendPeriodMs = {frame["sample_period_ms"]};
constexpr int expectedDataOffsets[] = {offsets};
constexpr int expectedDataProperties = {_cpp_properties(frame["data"]["access"])};
constexpr int expectedConfigProperties = {_cpp_properties(frame["config"]["access"])};
constexpr int expectedDefaultMode = {modes["default"]};
constexpr int expectedActiveModes[] = {_cpp_ints([mode["id"] for mode in modes["active"]])};
constexpr int expectedReservedModes[] = {_cpp_ints(modes["reserved"])};
constexpr float expectedSelectionMinimum = {selection["minimum"]!r}f;
constexpr float expectedSelectionMaximumExclusive = {selection["maximum_exclusive"]!r}f;
"""


def _build_and_run(
    tmp_path: Path, sketch: Path
) -> tuple[subprocess.CompletedProcess[str], subprocess.CompletedProcess[str] | None]:
    compiler = shutil.which(os.environ.get("CXX", "c++"))
    assert compiler is not None, "Host firmware tests require a C++17 compiler (CXX or c++)."
    header = tmp_path / "expected_protocol.h"
    header.write_text(_expected_header(), encoding="utf-8")
    executable = tmp_path / "firmware-behavior"
    build = subprocess.run(
        [
            compiler,
            "-std=c++17",
            "-Wall",
            "-Wextra",
            "-Werror",
            "-pedantic",
            "-I",
            str(REPO_ROOT / "tests/firmware/doubles"),
            "-include",
            str(header),
            f'-DSKETCH_SOURCE="{sketch}"',
            str(REPO_ROOT / "tests/firmware/behavior.cpp"),
            "-o",
            str(executable),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if build.returncode != 0:
        return build, None
    return build, subprocess.run([str(executable)], capture_output=True, text=True, check=False)


def test_actual_firmware_with_controlled_ble_sensors_and_clock(tmp_path) -> None:
    build, run = _build_and_run(tmp_path, SKETCH)
    assert build.returncode == 0, build.stderr
    assert run is not None and run.returncode == 0, run.stderr if run else ""


MUTATIONS = {
    "local-name-removed": ('  BLE.setLocalName("phyphox-sense");\n', ""),
    "device-name": ('BLE.setDeviceName("phyphox-sense")', 'BLE.setDeviceName("phyphox-sensor")'),
    "local-name": ('BLE.setLocalName("phyphox-sense")', 'BLE.setLocalName("phyphox")'),
    "service-uuid": ("cddf0001-30f7", "cddf0009-30f7"),
    "data-uuid": ("cddf1002-30f7", "cddf1009-30f7"),
    "config-uuid": ("cddf1003-30f7", "cddf1009-30f7"),
    "data-not-notify": ("kDataCharUuid, BLENotify,", "kDataCharUuid, BLERead,"),
    "config-not-writable": ("BLERead | BLEWrite", "BLERead"),
    "payload-size": ("kPayloadSizeBytes = 20;", "kPayloadSizeBytes = 24;"),
    "service-not-added": ("  BLE.addService(phyphoxService);\n", ""),
    "config-char-not-added": ("  phyphoxService.addCharacteristic(configCharacteristic);\n", ""),
    "not-advertised": ("  BLE.advertise();\n", ""),
    "initial-config-write": (
        "  writeActiveModeToConfigCharacteristic();\n\n  BLE.advertise",
        "  BLE.advertise",
    ),
    "payload-offset": ("4, ch2", "5, ch2"),
    "codec-byte-order": ("buf[offset + 3] =", "buf[offset + 2] ="),
    "config-sentinel": ("kConfigWireSizeBytes + 1", "kConfigWireSizeBytes + 2"),
    "config-length-guard": ("valueLength() ==", "valueLength() !="),
    "default-mode": ("Mode mode = Mode::kAcceleration;", "Mode mode = Mode::kGyroscope;"),
    "mode-set": ("    Mode::kAnalogInputs,\n};", "};"),
    "selection-minimum": ("configValue < 0.5f", "configValue < 0.6f"),
    "selection-maximum": ("configValue >= 9.5f", "configValue >= 9.4f"),
    "selection-rounding": ("(int)roundf(configValue)", "(int)configValue"),
    "send-period": ("kSendPeriodMs = 50;", "kSendPeriodMs = 40;"),
}


@pytest.mark.parametrize("name", sorted(MUTATIONS))
def test_firmware_behavior_rejects_protocol_drift(tmp_path, name: str) -> None:
    old, new = MUTATIONS[name]
    source = SKETCH.read_text(encoding="utf-8")
    assert old in source, f"mutation {name} no longer matches the sketch"
    mutated = tmp_path / "mutated.ino"
    mutated.write_text(source.replace(old, new, 1), encoding="utf-8")
    assert mutated.read_text(encoding="utf-8") != source
    build, run = _build_and_run(tmp_path, mutated)
    # A mutant must still compile; detection has to come from a behavioral assertion.
    assert build.returncode == 0, f"mutation {name} broke the build:\n{build.stderr}"
    assert run is not None and run.returncode != 0, f"mutation {name} was not detected"
    assert "Assertion" in run.stderr, run.stderr
